set nocompatible

set t_Co=256
syntax enable
colorscheme rcr

set backup
set writebackup
set backupdir=$HOME/.vim/tmp
set directory=$HOME/.vim/tmp
set viminfo+=n$HOME/.vim/viminfo

set nu
set cul
set title
set lazyredraw
set autoindent
set splitbelow
set smartindent
set scrolloff=3
set backspace=2
set noexpandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
set gdefault
set autochdir
set shortmess=atI

let mapleader = ","

cnoremap w!! %!sudo tee > /dev/null %<CR>
cnoremap s!! mksession! $HOME/.vim/session.vim<CR>

inoremap jj <Esc>
inoremap {<CR> {<CR>}<Esc>O
inoremap /* /*  */<Esc>2<Left>i
inoremap // //

nnoremap . .`[
nnoremap ; :
nnoremap ' `
nnoremap <Space> i_<Esc>r
nnoremap j gj
nnoremap k gk
nnoremap gs :wincmd w<CR>
nnoremap <Leader>s :Vex!<CR>
nnoremap <Leader>t :Tex<CR>
nnoremap <Leader>m :silent !tput clear<CR>:!make<CR>

vnoremap / y/<C-r>0<CR>

set list
set listchars=tab:-\ ,trail:-

set hlsearch
set incsearch
set smartcase
set ignorecase
"can enter be more useful?
nnoremap <CR> :noh<Return><Esc>
autocmd InsertLeave * :setlocal hlsearch
autocmd InsertEnter * :setlocal nohlsearch

set laststatus=2
set statusline=\ %F
set statusline+=\ :\ %L
set statusline+=\ %p%%
set statusline+=\ %02.3c
set statusline+=\ %M
set statusline+=\ %r

autocmd VimResized * exe "normal! \<c-w>="

autocmd BufReadPost * if line("'\"") <= line("$") | exe "normal! g'\"" | endif
