set nocompatible

set t_Co=256
syntax enable
colorscheme rcr

set backup
set writebackup
set backupdir=$HOME/.vim/tmp
set directory=$HOME/.vim/tmp

set nu
set cul
set splitbelow
set splitright
set autoindent
set smartindent
set textwidth=0
set backspace=2
set noexpandtab   "Do not insert a number of spaces when tab is hit
set tabstop=4     "Width of an existing tab
set shiftwidth=4  "Number of spaces used for >> and <<
set softtabstop=4 "Width of a tab when inserting
set gdefault      "/g flag set by default on :s substitution
set timeoutlen=250

cmap w!! %!sudo tee > /dev/null %<CR>
inoremap jj <Esc>
nnoremap . .`[
nnoremap ; :
nnoremap <Space> i_<Esc>r
nnoremap j gj
nnoremap k gk
nnoremap w :wincmd w<CR>
noremap ss :Vex!<CR>
vnoremap / y/<C-r>0<CR>
   
set list
set listchars=tab:-\ 

set hlsearch
set smartcase
set ignorecase
nnoremap <CR> :noh<Return><Esc>
autocmd InsertLeave * :setlocal hlsearch
autocmd InsertEnter * :setlocal nohlsearch

set viminfo+=n$HOME/.vim/viminfo
autocmd BufReadPost * if line("'\"") <= line("$") | exe "normal! g'\"" | endif

set lazyredraw
vmap <C-c> y:call system('xclip -f -sel p \| xclip -sel c', @0)<CR>
nmap <C-v> :set paste<CR>O<Esc>:.!xclip -o -selection c<CR>:set nopaste<CR>


autocmd VimResized * exe "normal! \<c-w>="
