#!/bin/sh

mpd=$(ncmpcpp --now-playing '{%a - %t}|{%f}')
vol=$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')
mut=$(amixer get Master | tail -1 | grep "\[on\]")
if [ "$mut" = "" ]
  then vol="M $vol"
  else vol="$vol"
fi

xsetroot -name "$mpd  ~  $vol  ~  $(date +%a\ %b\ %e\ %R)"
