#!/bin/sh
#
# ~/.xinitrc

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

urxvtd -q -o -f

feh --no-fehbg --force-aliasing --bg-center /home/rcr/.wallpaper.jpg

amixer -q set Master off 100%

xset m 1 2
xset r rate 250 40
setxkbmap -option ctrl:nocaps
unclutter -idle 1 &

while true; do
	/home/rcr/scripts/setroot
	sleep 3
done &

(sleep 3 && urxvtc -title "Irc" -e "weechat-curses") &

exec dwm
