#!/bin/sh
#
# ~/.xinitrc

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

urxvtd -q -o -f

feh --bg-scale /home/robbinsr/.background.png

amixer set Master 100%

xset r rate 250 40
setxkbmap -option ctrl:nocaps

while true; do
	/home/robbinsr/scripts/setroot
	sleep 3
done &

(sleep 3 && urxvtc -title "Irc" -e "weechat-curses") &
(sleep 5 && urxvtc -title "Mutt" -e "mutt") &

exec dwm
