#!/bin/sh
#
# ~/.xinitrc

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

urxvtd -q -o -f

feh --bg-scale /home/robbinsr/.background.png

amixer set Master 100

xset r rate 250 40

/home/robbinsr/.config/dwm/scripts/setroot &

/home/robbinsr/.config/dwm/scripts/launch

exec dwm
