#!/bin/bash

#in /etc/rc.local:

#wpa_supplicant -i wlan0 -c /etc/wpa_supplicant.conf & 
#(sleep 3 && dhcpcd wlan0) &

#Try a few times, to give network a chance to connect
for count in {1..5}; do
	net=$(iwgetid)
	if [ "$net" != "" ]; then
		urxvtc -title Mutt -e mutt &
		urxvtc -title Irc -e weechat-curses &
		break
	fi
	sleep 5
done
