#!/bin/bash

while true; do
	mpd=$(ncmpcpp --now-playing '{%a - %t}|{%f}')
	vol=$(amixer get Master | tail -1 | sed 's/.*\[\([0-9]*%\)\].*/\1/')
	mut=$(amixer get Master | tail -1 | grep "\[on\]")
	net=$(cat /sys/class/net/wlan0/flags)
	if [ "$net" = "0x1003" ]
		then net="con"
		else net="dis"
	fi
	if [ "$mut" = "" ]
	  then vol="M $vol"
	  else vol="$vol"
	fi
	xsetroot -name "$mpd  ~  $net  ~  $vol  ~  $(date +%a\ %b\ %e\ \ %R)"
	sleep 3
done

